# Specify a specific version to avoid bugs
# FROM node:lts-alpine
FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# # Enable polling for file watching on Windows
# ENV CHOKIDAR_USEPOLLING=true
# # Set polling interval (in milliseconds) - default is 100ms
# ENV CHOKIDAR_INTERVAL=1000
# # Reduce CPU usage
# ENV WATCHPACK_POLLING=true

CMD ["npm", "run", "start"]