name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t youruser/react-poc -f Dockerfile.dev .
      # - run: docker build . --file Dockerfile --tag youruser/react-poc:$(date +%s)
      - run: docker run -e CI=true youruser/react-poc npm test
